apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-blackbox-exporter
  labels:
    app.kubernetes.io/name: monitoring-blackbox-exporter
    app.kubernetes.io/part-of: monitoring-blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-blackbox-exporter
      app.kubernetes.io/part-of: monitoring-blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monitoring-blackbox-exporter
        app.kubernetes.io/part-of: monitoring-blackbox-exporter
    spec:
      containers:
      - name: monitoring-blackbox-exporter
        image: prom/blackbox-exporter
        ports:
        - containerPort: 9115 

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-blackbox-exporter
  labels:
    app.kubernetes.io/name: monitoring-blackbox-exporter
    app.kubernetes.io/part-of: monitoring-blackbox-exporter
spec:
  ports:
  - port: 80
    targetPort: 9115
  selector:
    app.kubernetes.io/name: monitoring-blackbox-exporter
    app.kubernetes.io/part-of: monitoring-blackbox-exporter
