apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-prometheus
  labels:
    app.kubernetes.io/name: monitoring-prometheus
    app.kubernetes.io/part-of: monitoring-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-prometheus
      app.kubernetes.io/part-of: monitoring-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monitoring-prometheus
        app.kubernetes.io/part-of: monitoring-prometheus
    spec:
      containers:
      - name: monitoring-prometheus
        image: prom/prometheus:v2.33.3
        ports:
        - containerPort: 9090 

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-prometheus
  labels:
    app.kubernetes.io/name: monitoring-prometheus
    app.kubernetes.io/part-of: monitoring-prometheus
spec:
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app.kubernetes.io/name: monitoring-prometheus
    app.kubernetes.io/part-of: monitoring-prometheus
